/**
    This file is autogenerated using the command `yarn app-store:build --watch`.
    Don't modify this file manually.
**/
import { appDataSchema as facebooksocial_zod_ts } from "./facebooksocial/zod";
import { appDataSchema as googlecloudstorage_zod_ts } from "./googlecloudstorage/zod";
import { appDataSchema as linkedinsocial_zod_ts } from "./linkedinsocial/zod";
import { appDataSchema as mediumsocial_zod_ts } from "./mediumsocial/zod";
import { appDataSchema as twitterv1social_zod_ts } from "./twitterv1social/zod";
import { appDataSchema as xsocial_zod_ts } from "./xsocial/zod";
import { appDataSchema as youtubesocial_zod_ts } from "./youtubesocial/zod";

export const appDataSchemas = {
  facebooksocial: facebooksocial_zod_ts,
  googlecloudstorage: googlecloudstorage_zod_ts,
  linkedinsocial: linkedinsocial_zod_ts,
  mediumsocial: mediumsocial_zod_ts,
  twitterv1social: twitterv1social_zod_ts,
  xsocial: xsocial_zod_ts,
  youtubesocial: youtubesocial_zod_ts,
};
