/**
    This file is autogenerated using the command `yarn app-store:build --watch`.
    Don't modify this file manually.
**/
export const apiHandlers = {
  chatgptai: import("./chatgptai/api"),
  googlecloudstorage: import("./googlecloudstorage/api"),
  linkedinsocial: import("./linkedinsocial/api"),
  stripepayment: import("./stripepayment/api"),
  twitterv1social: import("./twitterv1social/api"),
  typeform: import("./typeform/api"),
  xconsumerkeyssocial: import("./xconsumerkeyssocial/api"),
  xsocial: import("./xsocial/api"),
};
