/**
    This file is autogenerated using the command `yarn app-store:build --watch`.
    Don't modify this file manually.
**/
import { appKeysSchema as googlecloudstorage_zod_ts } from "./googlecloudstorage/zod";
import { appKeysSchema as linkedinsocial_zod_ts } from "./linkedinsocial/zod";
import { appKeysSchema as twitterv1social_zod_ts } from "./twitterv1social/zod";
import { appKeysSchema as xsocial_zod_ts } from "./xsocial/zod";

export const appKeysSchemas = {
  googlecloudstorage: googlecloudstorage_zod_ts,
  linkedinsocial: linkedinsocial_zod_ts,
  twitterv1social: twitterv1social_zod_ts,
  xsocial: xsocial_zod_ts,
};
