/**
    This file is autogenerated using the command `yarn app-store:build --watch`.
    Don't modify this file manually.
**/
import { appDataSchema as facebooksocial_zod_ts } from "./facebooksocial/zod";
import { appDataSchema as googlecloudstorage_zod_ts } from "./googlecloudstorage/zod";
import { appDataSchema as instagramsocial_zod_ts } from "./instagramsocial/zod";
import { appDataSchema as linkedinsocial_zod_ts } from "./linkedinsocial/zod";
import { appDataSchema as threadssocial_zod_ts } from "./threadssocial/zod";
import { appDataSchema as twitterv1social_zod_ts } from "./twitterv1social/zod";
import { appDataSchema as xsocial_zod_ts } from "./xsocial/zod";

export const appDataSchemas = {
  facebooksocial: facebooksocial_zod_ts,
  googlecloudstorage: googlecloudstorage_zod_ts,
  instagramsocial: instagramsocial_zod_ts,
  linkedinsocial: linkedinsocial_zod_ts,
  threadssocial: threadssocial_zod_ts,
  twitterv1social: twitterv1social_zod_ts,
  xsocial: xsocial_zod_ts,
};
