export const allFormat = [
    { content: "If you're in {x function}, study:\n\n1. {skill 1}\n2. {skill 2}\n3. {skill 3}\n4. {skill 4}\n5. {skill 5}\n6. {skill 6}\n7. {skill 7}\n8. {skill 8}\n9. {skill 9}\n10. {skill 10}\n\n{X} is just {define x differently}." },
    { content: "“{X} has changed”\n\n1. {before}\n2. {before}\n3. {before}\n\nExactly! It's a {what it is changed to}\n\n1. {new}\n2. {new}\n3. {new}\n\nStop complaining and start “{the right thing}. This is the 2024 way to {X}." },
    { content: "The \"worst\" thing you can do in your {X}\n\nBringing others down to prove you're \"the best\".\n\nI see this on {X} all the time. Example:\n\n1. {mistake 1}\n\n2. {mistake 2}\n\n3. {mistake 3}\n\nRecognize the mistakes?\n\nThis is called \"{X}”. And it's wrong.\n\nIf anything, it makes your {X}  weaker.\n\nYou don't need to bring a method down to prove yours is better. Simply show why yours is \"good\"." },
    { content: "{X} can be confusing.\n\nThere are so many metrics to focus on.\n\n- {metric 1}\n- {metric 2}\n- {metric 3}\n- {metric 4}\n- {metric 5}\n\nThere are definitely some metrics that matter more than the others.\n\nI’ve been doing {X] for more than {X} years.\n\nI check for these things instead:\n\n1. {things to check}\n2. {things to check}\n3. {things to check}\n" },
    { content: "Understand that {X} isn’t:\n\n❌ {myth 1}\n❌ {myth 2}\n❌ {myth 3}\n❌ {myth 4}\n❌ {myth 5}\n\nBut, it is:\n\n✅ {truth 1}\n✅ {truth 1}\n✅ {truth 1}\n✅ {truth 1}\n✅ {truth 1}\n\nYour {X} helps to answer these questions:\n\n1. {short question 1}\n2. {short question 2}\n3. {short question 3}\n\n{one-line tip}" },
    { content: "{X} should be less about\n\n- {don’t do}\n- {don’t do}\n- {don’t do}\n- {don’t do}\n\n{X} should be more about\n\n- {do this}\n- {do this}\n- {do this}\n- {do this}\n\n{zinger}" },
    { content: "Why {userpersona} should do {X}:\n\n1. {benefit 1 in 10 words}\n2. {benefit 2 in 10 words}\n3. {benefit 3 in 10 words}\n4. {benefit 4 in 10 words}\n5. {benefit 5 in 10 words}\n\nBest case, {best case}.\n\nWorst case, {worst case}.\n\nThat's a win-win." },
    { content: "{{Did X today}}\n\n{{Some Context}}\n\nHere are {{X}} things, that I learned in {{X Time}}:\n\n1. {{Lesson1}}\n2. {{Lesson2}}\n3. {{Lesson3}}\n4. {{Lesson4}}\n5. {{Lesson5}}\n\nHope that helps" },
    { content: "[X] Ways To [Do Something]\n\n[Short, attention-grabbing intro to the list]\n\n[Number] [Insert Tip/Strategy]\n↪ [Explaing the tip/strategy in 5 words]\n↪ [Explaing the tip/strategy in 5 words]\n\n[Number] [Insert Tip/Strategy]\n↪ [Explaing the tip/strategy in 5 words]\n↪ [Explaing the tip/strategy in 5 words]\n\n[Number] [Insert Tip/Strategy]\n↪ [Explaing the tip/strategy in 5 words]\n↪ [Explaing the tip/strategy in 5 words]\n\n...(Continue until you reach the end of your list)\n\n[Summarize, give a quick overview of the tips/strategies, or provide additional advice]\n\n[Ask a question or prompt conversation]"},
    { content: "If you want to [increase your productivity/goal], here are [number of tips] tips for you:\n\n1. [First Tip]\n\n2. [Second Tip]\n\n3. [Third Tip]\n\nI apply ALL of this to my life and there is not a single day I am not grateful for keeping my focus on the things that are most important.\n\n[Client's Call to Action]" },
    { content: "I've read many books, but this one changed my life:\n\n(And it’s not {random popular book})\n\n→ {book name}\n\n4 lessons I learned\n\n👉🏼 1. [Lesson One Title].\n       - [Brief Lesson One Description]\n\n👉🏼 2. [Lesson Two Title].\n       - [Brief Lesson Two Description]\n\n👉🏼 3. [Lesson Three Title].\n       - [Brief Lesson Three Description]\n\n👉🏼4. [Lesson Four Title].\n  - [Brief Lesson Four Description]\n\nLearn these lessons → you'll become unstoppable." },
    { content: "There is one [item] that I would recommend to every [target audience]. \nBecause it will [benefit] in a way that you can’t imagine.\n\nThat’s what the [item] “[title]” did for me. It [impact on me].\n\nHere are [number] lessons from the [item] that will challenge how you think about [topic]:\n\n1. “[Lesson 1 title]”\n\n[Lesson 1 explanation]\n\n2. [Lesson 2 title]\n\n[Lesson 2 explanation]\n\n3. [Lesson 3 title]\n\n[Lesson 3 explanation]\n\n4. [Lesson 4 title]\n\n[Lesson 4 explanation]\n\n5. [Lesson 5 title]\n\n[Lesson 5 explanation]\n\nIf you have [experienced/used/read] the [item], I’d love to hear about your [desired feedback] in the comments.\"\n\n[Client's Call to Action]" },
    { content: "How to do {thing}:\n\nOld way\n\n{Way1}\n{Way2}\n{Way3}\n{Way4}\n\nNew Way\n\n{Way1}\n{Way2}\n{Way3}\n{Way4}\n\n{New} > {Old}" },
    { content: "I am an expert at using [Platform}.\n\nUnfortunately, I wasted [LongTime] because I was using the wrong [Actions].\n\nSave yourself [Time] by using these [X] hidden [Platform] features guaranteed to [Outcome]:\n\n[Feature1]\n\n[Description]\n\n[Feature2]\n\n[Description]\n\n[Feature3]\n\n[Description]\n\n[Feature4]\n\n[Description]\n\n[Feature5]\n\n[Description]" },
    { content: "[Topic] 101\n\nOver the past [X] years, I have [ShortCredibilityStatement].\n\nAnd I use the same [X][Technique] every time:\n\n[Technique] #1: [Name]\n\nHow it works:\n\n[Step1]\n\n[Step2]\n\n[Step3]\n\nThis simple [Technique] allows you to achieve [Outcome].\n\n[Technique] #2: [Name]\n\nHow it works:\n\n[Step1]\n\n[Step2]\n\n[Step3]\n\nQuick note: Don't do [WrongStep]. That's a mistake. These steps work better.\n\n[Technique] #3: [Name]\n\nHow it works:\n\nAvoid doing [X]\n\nDo [Y] instead\n\nIf you avoid [X] and do [Y], you'll unlock [Z] outcome.\n\nEasy, right?\n\n[Technique] #4: [Name]\n\nHow it works:\n\n[Step1]\n\n[Step2]\n\n[Step3]\n\nDo these 3 things, and you'll be wildly successful." },
    { content: "8 {X} Tools (these made me {benefit})\n\nSteal all these. . . .\n\n1. Tool 1\n2. Tool 2\n3. Tool 3\n4. Tool 4\n5. Tool 5\n6. Tool 6\n7. Tool 7\n8. Tool 8\n\n{relevant persona}, what tool are you using?"  },
    { content: "I asked [X] [Niche] leaders one simple question:\n\n“What early career mistake will you never make again?”\n\nThe result: [X] profound mistakes everyone (from interns to executives) should avoid in their career.\n\nLet’s dive in:\n\nMistake 1: [Mistake1]\n\nToo often, [Role] chooses to [WrongDecision].\n\nInstead, [Role] should be focused on [RightDecision].\n\nThis is what ends up making the biggest difference.\n\nMistake 2: [Mistake2]\n\nA good [Role] can [GoodOutcome].\n\nA bad [Role] can [BadOutcome].\n\nBut a legendary [Role] can [GiantOutcome].\n\nMistake 3: [Mistake3]\n\nUntil you’ve [Milestone], don’t take your eye off the ball.\n\n[”RelevantQuote”].\n\nMistake 4: [Mistake4]\n\nTraditional wisdom says [TraditionalWisdom].\n\nBut that’s only true if you don’t do two things correctly:\n\n- [RightDecision1]\n- [RightDecision2]\n\nThen, [TraditionalWisdom] works great." },
    { content: "{years/month/days} ago, I had {low credibility in X}\n\n{X} years later, I just {LifeAchievement}.\n\nHere’s what those difficult years taught:\n\nLesson 1: {Lesson1}\n\nBack then, I used to {PositiveHabit}.\n\nDespite {NegativeObstacle}.\n\nThe only difference between then and now is {UnexpectedSmallDetail}.\n\nLesson 2: {Lesson2}\n\nFor the first few years, all I had was a {HumbleBeginning} and a {HumbleBeginning}.\n\nSince then, I’ve {PositiveOutcome}.\n\nBut can I tell you something?\n\nThose two {HumbleBeginnings} still mean more to me than anything.\n\nAll you need.\n\nLesson 3: {Lesson3}\n\nWhen I was first starting out, I was so determined to achieve {X} that I deprived myself of {ShortTermOutcome}.\n\nEveryone thought I was crazy.\n\nBut, {X} years later, I had successfully become {Outcome}.\n\nMeanwhile, a lot of people around me hadn’t moved at all.\n\nLesson 4: {Lesson4}\n\nI used to be very insecure about {Weakness}.\n\nI was ashamed that I didn’t have {Outcome}.\n\nAnd I didn’t {PositiveAction} because of it.\n\nIt took me a long time to realize those insecurities were holding me back.\n\nAnd no amount of success would fix them for me.\n\nLesson 5: {Lesson5}\n\nAfter college, a lot of people around me said:\n\n{WrongAdvice}\n\nBut then I’d watch them struggle to make progress in their own lives.\n\nA big part of success is going in a different direction.\n\nAnd remember: if it were easy, everyone would do it." },
    { content: "I remember [insert personal story].\n\nI was so [insert emotion] and thought to myself \n[insert what you thought].\n\nBut [insert what happened next].\n\nAnd that's when I realized \n - [1st realization].\n - [2nd realization].\n - [3rd realization].\n - [4th realization].\n\nPowerful lessons that I learned and have helped me \n 1. [insert how it's helped you].\n 2. [insert how it's helped you].\n 3. [insert how it's helped you].\n 4. [insert how it's helped you].\n\nIf you're ever feeling [insert emotion] or you're facing [insert challenge], just remember [insert moral of the story].\n\nIt might not be easy, but I promise you, it's worth it.\n\n[Insert question]" },
    { content: "I started [doing x], and here's what happened\n\n→ 1. [outcome 1]\n\n- [how 1]\n- [how 2]\n- [how 3]\n\n→ 2. [outcome 2]\n\n- [how 1]\n- [how 2]\n- [how 3]\n\n→ 3. [outcome 3]\n\n- [how 1]\n- [how 2]\n- [how 3]\n\n→ 4. [outcome 4]\n\n- [how 1]\n- [how 2]\n- [how 3]\n\nThat's it\n\nPS Ask me anything about [X]." },
    { content: "The old way vs. the new way of {Topic}\n\nOld way\n• {Way1}\n• {Way2}\n• {Way3}\n• {Way4}\n\nNew Way\n• {Way1}\n• {Way2}\n• {Way3}\n• {Way4}\n\nThe shift?\n\n{New} > {Old}\n\n{Call to Action}" },
    { content: "{topic} is HARD\n\nYou are expected to:\n\n- {myth 1} \n- {myth 2} \n- {myth 3}\n\nBut it’s (actually) really simple:\n\n- {reality 1}\n- {reality 2}\n- {reality 3}\n\n{topic} isn’t hard, but we’ve been conditioned to think it is.\n\n{relevant quote}"  },
    { content: "I committed to {{Task}} daily {{#}} months ago.\n\n(Without a {{relevant}} expertise)\n\n→ {{FirstOutcome}}\n→ {{SecondOutcome}}\n→ {{ThirdOutcome}}\n→ {{FourthOutcome}}\n→ {{FifthOutcome}}\n\nNot 100%, but what a wild journey.\n\nI'm convinced {{Task}} makes any {{TypeOfPerson}} better." },
    { content: "I improved {X} by {Y} by doing {DidThisThingToday}\n\n(13 lessons to {DidThisThingToday})\n\n1. {Lesson1} → {Tips in 3 words}\n2. {Lesson2} → {Tips in 3 words}\n3. {Lesson3} → {Tips in 3 words}\n4. {Lesson4} → {Tips in 3 words}\n5. {Lesson5} → {Tips in 3 words}\n6. {Lesson6} → {Tips in 3 words}\n7. {Lesson7} → {Tips in 3 words}\n8. {Lesson8} → {Tips in 3 words}\n9. {Lesson9} → {Tips in 3 words}\n10. {Lesson10} → {Tips in 3 words}\n11. {Lesson11} → {Tips in 3 words}\n12. {Lesson12} → {Tips in 3 words}\n13. {Lesson13} → {Tips in 3 words}\n\nHope that's helpful." },
    { content: "What would I do if I were {{DoingThing}} from scratch?\n\n(Someone asked me)\n\nMy answer:\n\n1. {{Thing1}}\n\n2. {{Thing2}}\n\n3. {{Thing3}}\n\n4. {{Thing4}}\n\nBetter {{DoingThing}}\n↳ {{benefit 1 in one word}}\n↳ {{benefit 2 in two words}}\n↳ {{benefit 3 in three words}}\n↳ {{benefit 4 in four words}}" },
    { content: "Last {Year/Month/Week} I did {NoteworthyAchievement}\n\nHere are the {X} steps of my journey:\n\n1. {Step 1 in 8 words}\n\n2. {Step 2 in 8 words}\n\n3. {Step 3 in 8 words}\n\nX. {Step X in 8 words}\n\nHope it's helpful to someone.\n\n{TakeawayMessage}\n\n\"If I can do it, you can do it too\"" },
    { content: "Stop {doing thing that doesn’t help}.\n\nIt’s time to {do thing}.\n\nHere’s what you don’t need:\n\n1. …\n2. …\n3. …\n4. …\n\nHere’s what you do need:\n\n→ …\n→ …\n→ …\n→ …\n\nStop {doing thing that doesn’t help 1}.\n" },
    { content: "My X biggest struggles as a new {{job role}} were:\n\n1. {{struggle in 2 words}}\n2. {{struggle in 4 words}}\n3. {{struggle in 6 words}}\n4. {{struggle in 8 words}}\n5. {{struggle in 10 words}}\n\n{{Call out to those in similar position}},\n\nHere’s my advice:\n\n1. {{way to overcome struggle in 10 words}}\n2. {{way to overcome struggle in 8 words}}\n3. {{way to overcome struggle in 6 words}}\n4. {{way to overcome struggle in 4 words}}\n5. {{way to overcome struggle in 2 words}}\n\nWhat else do you struggle with?\n" },
    { content: "My first 10 {thing}:\n\n- metrics\n- metrics\n- metrics\n- result\n\nMy last 10 {thing}:\n\n- metrics\n- metrics\n- metrics\n- result\n\n{Takeaway Message}\n\nCTA" },
    { content: "Most people suck at {topic}.\n\nBut if you avoid these 5 common mistakes, I guarantee you won’t.\n\n{Introduce mistake 1, in 3 words}.\n→ {Explain what it is in 10 words}.\n\nDo this instead\n↳ {Explain what they should do instead in 2 bullet points}.\n\n{Introduce mistake, in 3 words}. \n→ {Explain what it is in 10 words}.\n\nDo this instead\n↳ {Explain what they should do instead in 2 bullet points}.\n\n{Introduce mistake, in 3 words}. \n→ {Explain what it is in 10 words}.\n\nDo this instead\n↳ {Explain what they should do instead in 2 bullet points}.\n\n{Introduce mistake, in 3 words}. \n→ {Explain what it is in 10 words}.\n\nDo this instead\n↳ {Explain what they should do instead in 2 bullet points}.\n\n{Introduce mistake, in 3 words}. \n→ {Explain what it is in 10 words}.\n\nDo this instead\n↳ {Explain what they should do instead in 2 bullet points}.\n\n{Takeaway Message}\n\n{Call to action}" },
    { content: "\"Everyone on social media tells you to “{common advice}”\n\nBut almost nobody tells you how.\n\nIf they won’t, I will…\n\nSo, here’s how to {action} in 7 simple steps:\n\nStep 1 - {Introduce step, in 3 words}. \n\nExample\n↳ {Share an example in 10 words}.\n\nStep 2 - {Introduce step, in 3 words}. \n\nExample\n↳ {Share an example in 10 words}.\n\nStep 3 - {Introduce step, in 3 words}. \n\nExample\n↳ {Share an example}.\n\nStep 4 - {Introduce step, in 3 words}. \n\nExample\n↳ {Share an example}.\n\nStep 5 - {Introduce step, in 3 words}. \n\nExample\n↳ {Share an example}.\n\nStep 6 - {Introduce step, in 3 words}. \n\nExample\n↳ {Share an example}.\n\nStep 7 - {Introduce step, in 3 words}. \n\nExample\n↳ {Share an example}.\n\n{Takeaway Message}\n\n{Call to action}\"" },
    { content: "I spent {X}+ hours studying {topic} so you don’t have to.\n\nHere are {X} ingredients that will turn your {topic} into {valuable asset}:\n\n1. {Ingredient 1}\n\nThe number one thing you need from {ingredient 1} is {component}.\n\nSecondarily, you need {component}\n\nCombine both for {outcome}.\n\n2. {Ingredient 2}\n\nOn the other hand, you want to avoid words where your offer is irrelevant.\n\nThe classic example is {example}.\n\nUse {feature}, and then {take action}.\n\n3. {Ingredient 3}\n\n{Topic} is {characteristic}, so {ingredient 3} is very important.\n\nStart by {step 1}, and then {step 2} until you {get outcome}.\n\nDon’t {negative outcome}, but also don’t {make rash decision related to ingredient}.\n\n" },
];

export const StartScratch = [
    { content: "" },
];

export const ArticlePost = [
    { content: ""},
];
export const BookLearnings = [
    { content: "There is one [item] that I would recommend to every [target audience]. \nBecause it will [benefit] in a way that you can’t imagine.\n\nThat’s what the [item] “[title]” did for me. It [impact on me].\n\nHere are [number] lessons from the [item] that will challenge how you think about [topic]:\n\n1. “[Lesson 1 title]”\n\n[Lesson 1 explanation]\n\n2. [Lesson 2 title]\n\n[Lesson 2 explanation]\n\n3. [Lesson 3 title]\n\n[Lesson 3 explanation]" },
    { content: "I've read many books, but this one changed my life:\n\n(And it’s not {random popular book})\n\n→ {book name}\n\n4 lessons I learned\n\n👉🏼 1. [Lesson One Title].\n       - [Brief Lesson One Description]\n\n👉🏼 2. [Lesson Two Title].\n       - [Brief Lesson Two Description]\n\n👉🏼 3. [Lesson Three Title].\n       - [Brief Lesson Three Description]\n\n👉🏼4. [Lesson Four Title].\n       - [Brief Lesson Four Description]\n\nLearn these lessons → you'll become unstoppable." },
];
export const ShareTips = [
    { content: "\"Everyone on social media tells you to “{common advice}”\n\nBut almost nobody tells you how.\n\nIf they won’t, I will…\n\nSo, here’s how to {action} in 7 simple steps:\n\nStep 1 - {Introduce step, in 3 words}. \n\nExample\n↳ {Share an example in 10 words}.\n\nStep 2 - {Introduce step, in 3 words}. \n\nExample\n↳ {Share an example in 10 words}.\n\nStep 3 - {Introduce step, in 3 words}. \n\nExample\n↳ {Share an example}.\n\nStep 4 - {Introduce step, in 3 words}. \n\nExample\n↳ {Share an example}.\n\nStep 5 - {Introduce step, in 3 words}. \n\nExample\n↳ {Share an example}.\n\nStep 6 - {Introduce step, in 3 words}. \n\nExample\n↳ {Share an example}.\n\nStep 7 - {Introduce step, in 3 words}. \n\nExample\n↳ {Share an example}.\n\n{Takeaway Message}\n\n{Call to action}\"" },
    { content: "Stop {doing thing that doesn’t help}.\n\nIt’s time to {do thing}.\n\nHere’s what you don’t need:\n\n1. …\n2. …\n3. …\n4. …\n\nHere’s what you do need:\n\n→ …\n→ …\n→ …\n→ …\n\nStop {doing thing that doesn’t help 1}."  },
    { content: "What would I do if I were {{DoingThing}} from scratch?\n\n(Someone asked me)\n\nMy answer:\n\n1. {{Thing1}}\n\n2. {{Thing2}}\n\n3. {{Thing3}}\n\n4. {{Thing4}}\n\nBetter {{DoingThing}}\n↳ {{benefit 1 in one word}}\n↳ {{benefit 2 in two words}}\n↳ {{benefit 3 in three words}}\n↳ {{benefit 4 in four words}}" },
    { content: "If you want to [increase your productivity/goal], here are [number of tips] tips for you:\n\n1. [First Tip]\n\n2. [Second Tip]\n\n3. [Third Tip]\n\nI apply ALL of this to my life and there is not a single day I am not grateful for keeping my focus on the things that are most important.\n\n[Client's Call to Action]" },
    { content: "[X] Ways To [Do Something]\n\n[Short, attention-grabbing intro to the list]\n\n[Number] [Insert Tip/Strategy]\n↪ [Explaing the tip/strategy in 5 words]\n↪ [Explaing the tip/strategy in 5 words]\n\n[Number] [Insert Tip/Strategy]\n↪ [Explaing the tip/strategy in 5 words]\n↪ [Explaing the tip/strategy in 5 words]\n\n[Number] [Insert Tip/Strategy]\n↪ [Explaing the tip/strategy in 5 words]\n↪ [Explaing the tip/strategy in 5 words]\n\n...(Continue until you reach the end of your list)\n\n[Summarize, give a quick overview of the tips/strategies, or provide additional advice]\n\n[Ask a question or prompt conversation]" },
];
export const RecentLearning = [
    { content: "I spent {X}+ hours studying {topic} so you don’t have to.\n\nHere are {X} ingredients that will turn your {topic} into {valuable asset}:\n\n1. {Ingredient 1}\n\nThe number one thing you need from {ingredient 1} is {component}.\n\nSecondarily, you need {component}\n\nCombine both for {outcome}.\n\n2. {Ingredient 2}\n\nOn the other hand, you want to avoid words where your offer is irrelevant.\n\nThe classic example is {example}.\n\nUse {feature}, and then {take action}." },
    { content: "I improved {X} by {Y} by doing {DidThisThingToday}\n\n(13 lessons to {DidThisThingToday})\n\n1. {Lesson1} → {Tips in 3 words}\n2. {Lesson2} → {Tips in 3 words}\n3. {Lesson3} → {Tips in 3 words}\n4. {Lesson4} → {Tips in 3 words}\n5. {Lesson5} → {Tips in 3 words}\n6. {Lesson6} → {Tips in 3 words}\n7. {Lesson7} → {Tips in 3 words}\n8. {Lesson8} → {Tips in 3 words}\n9. {Lesson9} → {Tips in 3 words}\n10. {Lesson10} → {Tips in 3 words}\n11. {Lesson11} → {Tips in 3 words}\n12. {Lesson12} → {Tips in 3 words}\n13. {Lesson13} → {Tips in 3 words}\n\nHope that's helpful." },
    { content: "I committed to {{Task}} daily {{#}} months ago.\n\n(Without a {{relevant}} expertise)\n\n→ {{FirstOutcome}}\n→ {{SecondOutcome}}\n→ {{ThirdOutcome}}\n→ {{FourthOutcome}}\n→ {{FifthOutcome}}\n\nNot 100%, but what a wild journey.\n\nI'm convinced {{Task}} makes any {{TypeOfPerson}} better." },
    { content: "I started [doing x], and here's what happened\n\n→ 1. [outcome 1]\n\n- [how 1]\n- [how 2]\n- [how 3]\n\n→ 2. [outcome 2]\n\n- [how 1]\n- [how 2]\n- [how 3]\n\n→ 3. [outcome 3]\n\n- [how 1]\n- [how 2]\n- [how 3]" },
    { content: "{{Did X today}}\n\n{{Some Context}}\n\nHere are {{X}} things, that I learned in {{X Time}}:\n\n1. {{Lesson1}}\n2. {{Lesson2}}\n3. {{Lesson3}}\n4. {{Lesson4}}\n5. {{Lesson5}}\n\nHope that helps"},
];
export const FavouriteTool = [
    { content: "I am an expert at using [Platform}.\n\nUnfortunately, I wasted [LongTime] because I was using the wrong [Actions].\n\nSave yourself [Time] by using these [X] hidden [Platform] features guaranteed to [Outcome]:\n\n[Feature1]\n\n[Description]\n\n[Feature2]\n\n[Description]\n\n[Feature3]\n\n[Description]\n\n[Feature4]\n\n[Description]\n\n[Feature5]\n\n[Description]"},
];
export const ShareStruggle = [
    { content: "My X biggest struggles as a new {{job role}} were:\n\n1. {{struggle in 2 words}}\n2. {{struggle in 4 words}}\n3. {{struggle in 6 words}}\n4. {{struggle in 8 words}}\n5. {{struggle in 10 words}}\n\n{{Call out to those in similar position}},\n\nHere’s my advice:\n\n1. {{way to overcome struggle in 10 words}}\n2. {{way to overcome struggle in 8 words}}\n3. {{way to overcome struggle in 6 words}}\n4. {{way to overcome struggle in 4 words}}\n5. {{way to overcome struggle in 2 words}}\n\nWhat else do you struggle with?\n" },
    { content: "Last {Year/Month/Week} I did {NoteworthyAchievement}\n\nHere are the {X} steps of my journey:\n\n1. {Step 1 in 8 words}\n\n2. {Step 2 in 8 words}\n\n3. {Step 3 in 8 words}\n\nX. {Step X in 8 words}\n\nHope it's helpful to someone.\n\n{TakeawayMessage}\n\n\"If I can do it, you can do it too\"" },
    { content: "{years/month/days} ago, I had {low credibility in X}\n\n{X} years later, I just {LifeAchievement}.\n\nHere’s what those difficult years taught:\n\nLesson 1: {Lesson1}\n\nBack then, I used to {PositiveHabit}.\n\nDespite {NegativeObstacle}.\n\nThe only difference between then and now is {UnexpectedSmallDetail}.\n\nLesson 2: {Lesson2}\n\nFor the first few years, all I had was a {HumbleBeginning} and a {HumbleBeginning}.\n\nSince then, I’ve {PositiveOutcome}.\n"},
];

export const FormatContent = [
    { content: "" },
];